"Who was the muscle-bound 'Barbarian' played by Arnold Schwarzenegger in the 1981 movie?                                                                                                                                                                   "
"Conran                                            "
"Conan                                             "
"Connor                                            "
"Corran                                            "
"B"
"M"
"Who was Babe Ruth playing for in 1915 when he hit his first major-league home run?                                                                                                                                                                        "
"New York Yankees                                  "
"Boston Red Sox                                    "
"Baltimore Orioles                                 "
"Chicago Cubs                                      "
"D"
"M"
